dev_addr: 0.0.0.0:4000
docs_dir: docs

site_dir: site
site_name: Docker Proxy API
site_url: http://srault95.github.io/docker-proxy-api
site_description: Nginx Proxy with Basic auth and SSL for Docker Rest API
site_author: Stéphane RAULT 

repo_url: https://github.com/srault95/docker-proxy-api/

use_directory_urls: true
use_absolute_urls: true

theme: mkdocs

pages:
  - ['index.md', '**HIDDEN**']

